const x = 10;

try {
  x = 2;
} catch (error) {
  console.error(`Erro: ${error}`);
}

console.log("Continuando o c√≥digo...");
